// Generated by tools/convert_assets.py - do not edit by hand.
#pragma once
#include <stdint.h>

extern const uint8_t font_bits[918];
extern const uint8_t font_width[102];
#define TILE_SIZE 16
#define NUM_TILES 32
#define TILEF_WATER 1
#define TILEF_TREE 2
#define TILEF_OVERLAY 4
extern const uint16_t tile_pixels[8192];
extern const uint8_t tile_flags[32];

typedef struct { uint8_t x, y; int8_t to_map; uint8_t entry; } Warp;
typedef struct { uint8_t x, y; } Spawn;
typedef struct {
  const char *id;          // file name on the website (map, woods, ...)
  const char *area;        // area label
  uint8_t cols, rows;
  const uint8_t *tiles;    // cols*rows tile ids
  const uint8_t *over;     // cols*rows overlay tile ids (255 = none)
  const uint8_t *solid;    // cols*rows 0/1
  const uint8_t *enc;      // cols*rows 0/1 encounter cells
  const Warp *warps; uint8_t nwarps;
  const Spawn *spawns; const char *const *spawn_names; uint8_t nspawns;
} MapDef;
extern const uint8_t map_map_tiles[1200];
extern const uint8_t map_map_over[1200];
extern const uint8_t map_map_solid[1200];
extern const uint8_t map_map_enc[1200];
extern const uint8_t map_room1_tiles[30];
extern const uint8_t map_room1_over[30];
extern const uint8_t map_room1_solid[30];
extern const uint8_t map_room1_enc[30];
extern const uint8_t map_hall1_tiles[35];
extern const uint8_t map_hall1_over[35];
extern const uint8_t map_hall1_solid[35];
extern const uint8_t map_hall1_enc[35];
extern const uint8_t map_woods_tiles[3600];
extern const uint8_t map_woods_over[3600];
extern const uint8_t map_woods_solid[3600];
extern const uint8_t map_woods_enc[3600];
extern const uint8_t map_hall2_tiles[35];
extern const uint8_t map_hall2_over[35];
extern const uint8_t map_hall2_solid[35];
extern const uint8_t map_hall2_enc[35];
extern const uint8_t map_area3_tiles[180];
extern const uint8_t map_area3_over[180];
extern const uint8_t map_area3_solid[180];
extern const uint8_t map_area3_enc[180];
#define NUM_MAPS 6
#define MAP_MAP 0
#define MAP_ROOM1 1
#define MAP_HALL1 2
#define MAP_WOODS 3
#define MAP_HALL2 4
#define MAP_AREA3 5
extern const MapDef maps[NUM_MAPS];
#define HERO_W 16
#define HERO_H 24
extern const uint16_t hero_pixels[1536];
extern const uint16_t bob_pixels[384];
#define NUM_DREAMLINGS 33
#define CARD_PHOTO_W 80
#define CARD_PHOTO_H 100
// paletted pictures: 8-bit indices + 256-entry RGB15 palette per picture (index 0 = clear)
extern const uint8_t dreamling64_idx[135168];
extern const uint16_t dreamling64_pal[8448];
extern const uint8_t dreamling32_idx[33792];
extern const uint16_t dreamling32_pal[8448];
extern const uint8_t card_photo_idx[264000];
extern const uint16_t card_photo_pal[8448];
#define FRAME_W 180
#define FRAME_H 252
extern const uint16_t card_frame[45360];
#define LOGO_W 182
#define LOGO_H 56
extern const uint8_t logo_idx[10192];
extern const uint16_t logo_pal[256];
