name: Build Dreamlings DS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dreamlings.nds
        run: |
          make
          ls -la *.nds

      - uses: actions/upload-artifact@v4
        with:
          name: dreamlings-nds
          path: "*.nds"
